name: Dev Branch Build

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - Dev
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
      
      - name: Build
        run: npm run build
      
      - name: Verify build artifacts
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ dist directory missing - build failed!"
            exit 1
          fi
          
          # Check essential files
          for file in "dist/index.js" "dist/platform.js" "dist/accessory.js" "dist/api/sleepme-api.js"; do
            if [ ! -f "$file" ]; then
              echo "❌ Required file missing: $file"
              exit 1
            fi
          done
          
          echo "✅ Build verification passed!"
