name: Publish Dev Version

on:
  workflow_dispatch:

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Update dev version
        run: |
          # Get current version and add dev suffix if not present
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [[ $CURRENT_VERSION != *-dev* ]]; then
            NEW_VERSION="${CURRENT_VERSION}-dev.1"
          else
            # Increment dev version
            BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-dev\.[0-9]*$//')
            DEV_NUM=$(echo $CURRENT_VERSION | sed 's/.*-dev\.//')
            NEW_DEV_NUM=$((DEV_NUM + 1))
            NEW_VERSION="${BASE_VERSION}-dev.${NEW_DEV_NUM}"
          fi
          
          # Update package.json
          npm version $NEW_VERSION --no-git-tag-version
          
          echo "Publishing development version: $NEW_VERSION"
      
      - name: Publish to npm
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}