name: Manual Version and Publish

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version increment type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  manual-build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint

    - name: Clean
      run: npm run clean
      
    - name: Build TypeScript
      run: tsc
      
    - name: Build UI Files
      run: |
        mkdir -p dist/homebridge-ui
        cp -r homebridge-ui/. dist/homebridge-ui/
        
    - name: Verify Build
      run: |
        if [ ! -d "dist/homebridge-ui/public" ]; then
          echo "Error: dist/homebridge-ui/public directory is missing!"
          exit 1
        fi
        
        if [ ! -f "dist/homebridge-ui/public/index.html" ]; then
          echo "Error: index.html is missing from UI build!"
          exit 1
        fi
        
        echo "UI Files in dist:"
        find dist/homebridge-ui -type f | grep -v "node_modules" | sort
        
        echo "JS Files in UI:"
        find dist/homebridge-ui/public/js -type f | sort

    - name: Commit Build Artifacts
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add dist
        git commit -m "Build artifacts for release" || echo "No changes to commit"

    - name: Bump Version
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        npm version ${{ github.event.inputs.version_type || 'patch' }}
        git push
        git push --tags

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        tag_name: v${{ github.ref_name }}
