name: Publish to npm

on:
  push:
    branches:
      - main  # or your primary branch name
    paths:
      - 'package.json'  # Only trigger when package.json changes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This ensures all history and tags are fetched
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Use appropriate Node version
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Verify npm identity
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # Explicitly create an .npmrc file for authentication
      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          cat .npmrc | grep -v "_authToken"  # Show .npmrc content without exposing token
          npm config set access public
      
      # Check package ownership before attempting to publish
      - name: Check package ownership
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "Checking ownership for package: $PACKAGE_NAME"
          NPM_OWNER=$(npm owner ls $PACKAGE_NAME || echo "Package not found")
          echo "Current ownership: $NPM_OWNER"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
